export const chileCities = [
  "Arica",
  "Iquique",
  "Antofagasta",
  "Calama",
  "Copiapo",
  "La Serena",
  "Coquimbo",
  "Valparaiso",
  "Vina del Mar",
  "Santiago",
  "Rancagua",
  "Talca",
  "Concepcion",
  "Temuco",
  "Valdivia",
  "Puerto Montt",
  "Punta Arenas",
] as const
